// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:ff4d636a-e363-4a0b-8ceb-ad02f878a502",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_fZkLgxBfW",
    "aws_user_pools_web_client_id": "5crd8kb164udqvjhpqlp3boaji",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://cughdeh6jjag5ivwu6e7twd54e.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-dpso3mqktrbglpa72iiyves4p4"
};


export default awsmobile;
